create table tb_belonging (position integer, list_id bigint not null, music_id bigint not null, primary key (list_id, music_id)) engine=InnoDB;
create table tb_music (music_year integer, id bigint not null auto_increment, artist varchar(255), genre varchar(255), img_url varchar(255), long_description TEXT, short_description TEXT, title varchar(255), primary key (id)) engine=InnoDB;
create table tb_musica_list (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
alter table tb_belonging add constraint FKjtl9qvckhocq8ca83lx6qwnxj foreign key (music_id) references tb_music (id);
alter table tb_belonging add constraint FKn2v83siqw0y1bgbb02h360q56 foreign key (list_id) references tb_musica_list (id);
INSERT INTO tb_music (title, music_year, genre, artist, img_url, short_description, long_description) VALUES ('Bohemian Rhapsody', 1975, 'Rock', 'Queen', 'https://m.media-amazon.com/images/I/61VWSXTDFfL._UF1000,1000_QL80_.jpg', 'One of the most iconic rock songs.', 'Bohemian Rhapsody by Queen, released in 1975, blends ballad, opera, and hard rock in a single epic track.');
INSERT INTO tb_music (title, music_year, genre, artist, img_url, short_description, long_description) VALUES ('Imagine', 1971, 'Pop', 'John Lennon', 'https://upload.wikimedia.org/wikipedia/pt/9/9c/John_Lennon_-_Imagine.jpg', 'A hymn of peace and reflection.', 'Imagine, by John Lennon, invites the listener to envision a world without barriers or conflict. It is considered one of the most influential songs in history.');
INSERT INTO tb_music (title, music_year, genre, artist, img_url, short_description, long_description) VALUES ('Smells Like Teen Spirit', 1991, 'Grunge', 'Nirvana', 'https://upload.wikimedia.org/wikipedia/pt/3/3c/Smells_Like_Teen_Spirit.jpg', '90s generation anthem.', 'Released by Nirvana, this song became a symbol of the grunge movement and marked a generation with its raw energy and striking lyrics.');
INSERT INTO tb_music (title, music_year, genre, artist, img_url, short_description, long_description) VALUES ('Thriller', 1982, 'Pop', 'Michael Jackson', 'https://m.media-amazon.com/images/I/81ogsUqshzL.jpg', 'Michael Jackson''s biggest hit.', 'Thriller is known for its groundbreaking music video and danceable beat. It revolutionized the music industry.');
INSERT INTO tb_music (title, music_year, genre, artist, img_url, short_description, long_description) VALUES ('Like a Rolling Stone', 1965, 'Folk Rock', 'Bob Dylan', 'https://upload.wikimedia.org/wikipedia/pt/b/b5/LikeaRollingStone.jpg', 'Revolutionized rock with its lyrics.', 'Bob Dylan redefined what a pop song could be with Like a Rolling Stone, blending poetry and social critique.');
INSERT INTO tb_music (title, music_year, genre, artist, img_url, short_description, long_description) VALUES ('Hey Jude', 1968, 'Rock', 'The Beatles', 'https://cdn-images.dzcdn.net/images/cover/9ef8134abe2e9e87676368a6cffff863/0x1900-000000-80-0-0.jpg', 'An emotional Beatles ballad.', 'Hey Jude was written by Paul McCartney to comfort Julian Lennon, John Lennon''s son, during his parents'' divorce.');
INSERT INTO tb_music (title, music_year, genre, artist, img_url, short_description, long_description) VALUES ('Hotel California', 1977, 'Rock', 'Eagles', 'https://akamai.sscdn.co/letras/360x360/albuns/6/c/9/c/363051404156912.jpg', 'A critique of California lifestyle.', 'Hotel California features an engaging melody and symbolic lyrics exploring hedonism and decadence.');
INSERT INTO tb_music (title, music_year, genre, artist, img_url, short_description, long_description) VALUES ('Stairway to Heaven', 1971, 'Rock', 'Led Zeppelin', 'https://m.media-amazon.com/images/I/616YVJmiuAL._AC_UF1000,1000_QL80_.jpg', 'A classic rock masterpiece.', 'Regarded as one of the greatest songs of all time, Stairway to Heaven is known for its gradual buildup and iconic guitar solo.');
INSERT INTO tb_music (title, music_year, genre, artist, img_url, short_description, long_description) VALUES ('What''s Going On', 1971, 'Soul', 'Marvin Gaye', 'https://upload.wikimedia.org/wikipedia/pt/c/c4/CapaMarvin_Gaye.jpg', 'A socially conscious song.', 'Marvin Gaye addressed issues like war and civil rights in What''s Going On, a landmark in soul music.');
INSERT INTO tb_musica_list (name) VALUES ('Rock');
INSERT INTO tb_musica_list (name) VALUES ('Pop');
INSERT INTO tb_musica_list (name) VALUES ('Grunge');
INSERT INTO tb_musica_list (name) VALUES ('Folk Rock');
INSERT INTO tb_musica_list (name) VALUES ('Soul');
INSERT INTO tb_belonging (list_id, music_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, music_id, position) VALUES (1, 6, 1);
INSERT INTO tb_belonging (list_id, music_id, position) VALUES (1, 7, 2);
INSERT INTO tb_belonging (list_id, music_id, position) VALUES (1, 8, 3);
INSERT INTO tb_belonging (list_id, music_id, position) VALUES (2, 2, 0);
INSERT INTO tb_belonging (list_id, music_id, position) VALUES (2, 4, 1);
INSERT INTO tb_belonging (list_id, music_id, position) VALUES (3, 3, 0);
INSERT INTO tb_belonging (list_id, music_id, position) VALUES (4, 5, 0);
INSERT INTO tb_belonging (list_id, music_id, position) VALUES (5, 9, 0);
